<a href="https://colab.research.google.com/github/lugosidomotor/ML/blob/master/ML_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

In [2]:
from google.colab import files
files.upload()

Saving verified_pb.data to verified_pb.data


{'verified_pb.data': b'1\t1\t1\tIY\t160.\t240.\t2280.\t2850.\n1\t1\t1\tIY\t186.\t280.\t2400.\t2790.\n1\t1\t2\tIH\t203.\t390.\t2030.\t2640.\n1\t1\t2\tIH\t192.\t310.\t1980.\t2550.\n1\t1\t3\tEH\t161.\t490.\t1870.\t2420.\n1\t1\t3\t*EH\t155.\t570.\t1700.\t2600.\n1\t1\t4\t*AE\t140.\t560.\t1820.\t2660.\n1\t1\t4\tAE\t180.\t630.\t1700.\t2550.\n1\t1\t5\tAH\t144.\t590.\t1250.\t2620.\n1\t1\t5\tAH\t148.\t620.\t1300.\t2530.\n1\t1\t6\tAA\t148.\t740.\t1070.\t2490.\n1\t1\t6\tAA\t170.\t800.\t1060.\t2640.\n1\t1\t7\t*AO\t161.\t600.\t970.\t2280.\n1\t1\t7\t*AO\t158.\t660.\t980.\t2220.\n1\t1\t8\tUH\t163.\t440.\t1120.\t2210.\n1\t1\t8\tUH\t190.\t400.\t1070.\t2280.\n1\t1\t9\tUW\t160.\t240.\t1040.\t2150.\n1\t1\t9\tUW\t157.\t270.\t930.\t2280.\n1\t1\t10\tER\t177.\t370.\t1520.\t1670.\n1\t1\t10\tER\t164.\t460.\t1330.\t1590.\n1\t2\t1\tIY\t147.\t220.\t2220.\t2910.\n1\t2\t1\tIY\t148.\t210.\t2360.\t3250.\n1\t2\t2\tIH\t141.\t410.\t1890.\t2680.\n1\t2\t2\tIH\t139.\t420.\t1850.\t2500.\n1\t2\t3\tEH\t136.\t500.\t1760.\t2590.\

In [52]:
df = pd.read_table('verified_pb.data', delim_whitespace=True, names=["Sex", "SPKR", "Phoneme-Number", "Phoneme-Ascii","F0", "F1", "F2", "F3" ])
df.head(10)

Sex  SPKR  Phoneme-Number Phoneme-Ascii     F0     F1      F2      F3
0    1     1               1            IY  160.0  240.0  2280.0  2850.0
1    1     1               1            IY  186.0  280.0  2400.0  2790.0
2    1     1               2            IH  203.0  390.0  2030.0  2640.0
3    1     1               2            IH  192.0  310.0  1980.0  2550.0
4    1     1               3            EH  161.0  490.0  1870.0  2420.0
5    1     1               3           *EH  155.0  570.0  1700.0  2600.0
6    1     1               4           *AE  140.0  560.0  1820.0  2660.0
7    1     1               4            AE  180.0  630.0  1700.0  2550.0
8    1     1               5            AH  144.0  590.0  1250.0  2620.0
9    1     1               5            AH  148.0  620.0  1300.0  2530.0

In [53]:
#CLEAN DATA FROM *
df['Phoneme-Ascii'] = df['Phoneme-Ascii'].str.replace('*', '')
df.head(10)

Sex  SPKR  Phoneme-Number Phoneme-Ascii     F0     F1      F2      F3
0    1     1               1            IY  160.0  240.0  2280.0  2850.0
1    1     1               1            IY  186.0  280.0  2400.0  2790.0
2    1     1               2            IH  203.0  390.0  2030.0  2640.0
3    1     1               2            IH  192.0  310.0  1980.0  2550.0
4    1     1               3            EH  161.0  490.0  1870.0  2420.0
5    1     1               3            EH  155.0  570.0  1700.0  2600.0
6    1     1               4            AE  140.0  560.0  1820.0  2660.0
7    1     1               4            AE  180.0  630.0  1700.0  2550.0
8    1     1               5            AH  144.0  590.0  1250.0  2620.0
9    1     1               5            AH  148.0  620.0  1300.0  2530.0

In [39]:
#GET THE FIRST 4 MALE, FIRST 4 FEMALE AND FIRST 3 CHILD

male = []
female = []
child = []

for row in df.iterrows():
  if row[1][0] == 1 and row[1][1] not in male and len(male) < 4:
    male.append(row[1][1])

for row in df.iterrows():
  if row[1][0] == 2 and row[1][1] not in female and len(female) < 4:
    female.append(row[1][1])
  
for row in df.iterrows():
  if row[1][0] == 3 and row[1][1] not in child and len(child) < 2:
    child.append(row[1][1])


test = male + female + child
print(test)


[1, 2, 3, 4, 34, 35, 36, 37, 62, 63]


In [54]:
#CREATE TEST SET
df_test =  df.loc[df['SPKR'].isin(test)]

In [55]:
#CREATE TRAIN SET
df_train = pd.concat([df, df_test]).drop_duplicates(keep=False)

In [86]:
#TARGET
X_train = df_train.iloc[:,2].values
X_test = df_test.iloc[:,2].values

#FEATURE
Y_train = df_train.iloc[:, 4:8].values
Y_test = df_test.iloc[:, 4:8].values

#TRAIN THE MODEL
tree = DecisionTreeClassifier().fit(X_train.reshape(-1, 1), Y_train)

#PREDICTION
tree_prediction = tree.predict(X_test.reshape(-1, 1))

#PREDICTED VALUES
print(tree_prediction)
#REAL VALUES
Y_test

[[ 250.  300. 2800. 3400.]
 [ 250.  300. 2800. 3400.]
 [ 250.  400. 2500. 2450.]
 [ 250.  400. 2500. 2450.]
 [ 125.  500. 2300. 2500.]
 [ 125.  500. 2300. 2500.]
 [ 200.  660. 1800. 2400.]
 [ 200.  660. 1800. 2400.]
 [ 125.  770. 1500. 2700.]
 [ 125.  770. 1500. 2700.]
 [ 250.  670. 1350. 2680.]
 [ 250.  670. 1350. 2680.]
 [ 120.  600.  850. 2500.]
 [ 120.  600.  850. 2500.]
 [ 140.  450. 1200. 2200.]
 [ 140.  450. 1200. 2200.]
 [ 140.  350. 1000. 2300.]
 [ 140.  350. 1000. 2300.]
 [ 128.  510. 1300. 1600.]
 [ 128.  510. 1300. 1600.]
 [ 250.  300. 2800. 3400.]
 [ 250.  300. 2800. 3400.]
 [ 250.  400. 2500. 2450.]
 [ 250.  400. 2500. 2450.]
 [ 125.  500. 2300. 2500.]
 [ 125.  500. 2300. 2500.]
 [ 200.  660. 1800. 2400.]
 [ 200.  660. 1800. 2400.]
 [ 125.  770. 1500. 2700.]
 [ 125.  770. 1500. 2700.]
 [ 250.  670. 1350. 2680.]
 [ 250.  670. 1350. 2680.]
 [ 120.  600.  850. 2500.]
 [ 120.  600.  850. 2500.]
 [ 140.  450. 1200. 2200.]
 [ 140.  450. 1200. 2200.]
 [ 140.  350. 1000. 2300.]
 

array([[ 160.,  240., 2280., 2850.],
       [ 186.,  280., 2400., 2790.],
       [ 203.,  390., 2030., 2640.],
       [ 192.,  310., 1980., 2550.],
       [ 161.,  490., 1870., 2420.],
       [ 155.,  570., 1700., 2600.],
       [ 140.,  560., 1820., 2660.],
       [ 180.,  630., 1700., 2550.],
       [ 144.,  590., 1250., 2620.],
       [ 148.,  620., 1300., 2530.],
       [ 148.,  740., 1070., 2490.],
       [ 170.,  800., 1060., 2640.],
       [ 161.,  600.,  970., 2280.],
       [ 158.,  660.,  980., 2220.],
       [ 163.,  440., 1120., 2210.],
       [ 190.,  400., 1070., 2280.],
       [ 160.,  240., 1040., 2150.],
       [ 157.,  270.,  930., 2280.],
       [ 177.,  370., 1520., 1670.],
       [ 164.,  460., 1330., 1590.],
       [ 147.,  220., 2220., 2910.],
       [ 148.,  210., 2360., 3250.],
       [ 141.,  410., 1890., 2680.],
       [ 139.,  420., 1850., 2500.],
       [ 136.,  500., 1760., 2590.],
       [ 135.,  510., 1710., 2380.],
       [ 128.,  690., 1610., 2560.],
 